### ISSUE TITLE
Any future plans?

### ISSUE THREAD

**Issue by dumblob** [mobarski/fabris#1]
I like concatenative languages and this one seems quite interesting (and "modern"). Any plans to continue development? Is Fabris being used somewhere in production?

**Comment by mobarski** [comment]
Well no, but actually yes ;)
Fabris is a dead project now BUT I've again started working on a concatenative language (Morty). This time I have a bit different approach but the language will be similar to Fabris.

**Comment by dumblob** [comment]
Nice! I've subscribed to the Morty repo and will follow it to see what you have in your mind :wink:.
